apiVersion: v2
name: hashbrown
description: A Helm chart for Hashbrown Project

maintainers: 
  - name: Vikram Somavaram
    email: vikramsomavaram@gmail.com

type: application
version: 0.1.0
appVersion: "1.16.0"
